#include <Arduino.h>

/* DRIVER PINS */
#define RIGHT_DRIVE_A PB_8
#define RIGHT_DRIVE_B PB_9
#define LEFT_DRIVE_A PA_8
#define LEFT_DRIVE_B PA_9

/* RELAY PINS */
#define RELAY_CH1 PB13 // Left Arm
#define RELAY_CH2 PB14 // Right Arm
#define RELAY_CH3 PB12
// BOTH 12 & 14 for wall

/* BOMB DETECTION PINS */
#define BOMB_DETECT_SERVO_LEFT A0
#define BOMB_DETECT_SERVO_RIGHT A1

#define BOMB_DETECT_SENSOR_LEFT PB11
#define BOMB_DETECT_SENSOR_RIGHT PB10

/* IR PINS */
#define IR_INPUT_PIN_LEFT PB0 
#define IR_INPUT_PIN_RIGHT PA7 

/* TAPE TRACKING PINS */
#define TAPE_INPUT_PIN_LEFT PA4
#define TAPE_INPUT_PIN_RIGHT PA5

/* IDOL DETECTION PINS */
#define ECHO_PIN_RIGHT PB3
#define TRIGGER_PIN_RIGHT PB4

#define ECHO_PIN_LEFT PA11
#define TRIGGER_PIN_LEFT PA12

/* WALL PINS */
#define LIMIT_SWITCH_WALL PB6

/* RELEASE PINS */
#define RELEASE_SERVO PB5