#include <Arduino.h>

/* Driver Pin */
#define RIGHT_DRIVE_A PB_8
#define RIGHT_DRIVE_B PB_9
#define LEFT_DRIVE_A PA_8
#define LEFT_DRIVE_B PA_9

/* Relay Pins */
#define RELAY_CH1 PB13 // Left Arm
#define RELAY_CH2 PB14 // Right Arm
#define RELAY_CH3 PB12
// BOTH 12 & 14 for wall

/* BOMB DETECTION PINS */
#define BOMB_DETECT_SERVO_LEFT B10
#define BOMB_DETECT_SERVO_RIGHT B11

#define BOMB_DETECT_SENSOR_LEFT PA2 
#define BOMB_DETECT_SENSOR_RIGHT PA3

/* IR PINS */
#define IR_INPUT_PIN_LEFT PB0 
#define IR_INPUT_PIN_RIGHT PA7 

/* TAPE TRACKING PINS */
#define TAPE_INPUT_PIN_LEFT PA4
#define TAPE_INPUT_PIN_RIGHT PA5

/* IDOL DETECTION PINS */
#define ECHO_PIN PB3
#define TRIGGER_PIN PB4